-- XYANI876 Collection Supabase setup
-- Run this entire file once in Supabase Dashboard > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price integer not null check (price >= 0),
  category text not null default 'Bags',
  stock integer not null default 0 check (stock >= 0),
  badge text not null default '',
  image_url text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('XY' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_name text not null,
  phone text not null,
  email text,
  delivery_method text not null,
  address text,
  parish text,
  knutsford_branch text,
  payment_method text not null,
  payment_status text not null default 'Pending',
  status text not null default 'New',
  notes text,
  total integer not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on table public.admins from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;

grant select on table public.products to anon, authenticated;
grant insert on table public.orders to anon, authenticated;
grant insert on table public.order_items to anon, authenticated;
grant select, insert, update, delete on table public.products to authenticated;
grant select, update on table public.orders to authenticated;
grant select on table public.order_items to authenticated;
grant select on table public.admins to authenticated;
grant usage, select on sequence public.order_items_id_seq to anon, authenticated;

-- Public shoppers can only see products that are enabled.
drop policy if exists "public can view active products" on public.products;
create policy "public can view active products" on public.products for select to anon, authenticated using (active = true or exists (select 1 from public.admins a where a.user_id = (select auth.uid())));

-- Only explicitly registered admin users can manage products.
drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products for insert to authenticated with check (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products for update to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid()))) with check (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products for delete to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));

-- Checkout can create orders, but public visitors cannot read other customers' orders.
drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders" on public.orders for insert to anon, authenticated with check (status = 'New' and payment_status = 'Pending');
drop policy if exists "admins view orders" on public.orders;
create policy "admins view orders" on public.orders for select to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));
drop policy if exists "admins update orders" on public.orders;
create policy "admins update orders" on public.orders for update to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid()))) with check (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));

drop policy if exists "public can create order items" on public.order_items;
create policy "public can create order items" on public.order_items for insert to anon, authenticated with check (exists (select 1 from public.orders o where o.id = order_id));
drop policy if exists "admins view order items" on public.order_items;
create policy "admins view order items" on public.order_items for select to authenticated using (exists (select 1 from public.admins a where a.user_id = (select auth.uid())));

drop policy if exists "admin can view own admin record" on public.admins;
create policy "admin can view own admin record" on public.admins for select to authenticated using (user_id = (select auth.uid()));

-- Seed starter products only if catalog is empty.
insert into public.products(name,price,category,stock,badge)
select * from (values
 ('Midnight Statement Bag',4000,'Bags',4,'NEW'),
 ('Blush Mini Bag',4000,'Bags',2,'HOT'),
 ('Classic Shoulder Bag',4500,'Bags',0,'SOLD OUT'),
 ('Everyday Crossbody',3500,'Bags',6,''),
 ('Golden Detail Set',2500,'Accessories',3,'NEW'),
 ('Pink Statement Piece',3000,'Accessories',5,''),
 ('Night Out Mini',4000,'Bags',1,'LAST ONE'),
 ('Complete The Look Set',5000,'Accessories',0,'SOLD OUT')
) as seed(name,price,category,stock,badge)
where not exists (select 1 from public.products);

-- AFTER creating your admin account in Authentication > Users, run this separately,
-- replacing the UUID with that user's ID:
-- insert into public.admins(user_id,email) values ('YOUR-AUTH-USER-UUID','xyani876collections@gmail.com');
